# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Admin.create!(
  email: "admin@admin.com",
  password: "aaaaaa"
)

EndUser.create!(
  [{
    last_name: "Guest",
    first_name: "User",
    last_name_kana: "ゲスト",
    first_name_kana: "ユーザー",
    email: "guest@com",
    phone_number: "0312345678",
  },
  {
    last_name: "二階堂",
    first_name: "二江",
    last_name_kana: "ニカイドウ",
    first_name_kana: "フタエ",
    email: "222@gmail.com",
    password: "222222",
    phone_number: "0322222222",
  },
  {
    last_name: "三山",
    first_name: "三助",
    last_name_kana: "ミヤマ",
    first_name_kana: "サンスケ",
    email: "333@gmail.com",
    password: "333333",
    phone_number: "0333333333",
  },
  {
    last_name: "四道",
    first_name: "四平",
    last_name_kana: "シドウ",
    first_name_kana: "ヨンペイ",
    email: "444@gmail.com",
    password: "444444",
    phone_number: "0344444444",
  },
  {
    last_name: "五郷",
    first_name: "彰五",
    last_name_kana: "ゴゴウ",
    first_name_kana: "ショウゴ",
    email: "555@gmail.com",
    password: "555555",
    phone_number: "0355555555",
  },
  {
    last_name: "六町",
    first_name: "六子",
    last_name_kana: "ロクマチ",
    first_name_kana: "ムツコ",
    email: "666@gmail.com",
    password: "666666",
    phone_number: "0366666666",
  },
])

Consultation.create!(
  [
  {
    end_user_id: 2,
    title: "戸建て住宅検討中です。",
    body: "現在借家で、子ども（未就学児）と夫婦の三人暮らしです。貯金が少したまってきたので、戸建て購入を検討しています。頭金や諸費用どのくらいで購入できたのか、実経験者の方にお伺いしたいです。",
  },
  {
    end_user_id: 2,
    title: "引っ越し時期について。",
    body: "戸建て購入を検討しています。子どもが1人いて未就学児ですが、小学校は出来るだけ転校しない方が良いでしょうか？引っ越し時期に関して注意点等皆様の経験をお聞かせください。",
  },
  {
    end_user_id: 2,
    title: "節約の仕方。",
    body: "現在借家で、子ども（未就学児）と夫婦の三人暮らしです。戸建て購入を検討しているため、もう少し貯金のペースをあげたいと思っており、無理なく貯金できる知恵がある方は教えていただきたいです。",
  },
  {
    end_user_id: 2,
    title: "子どもの習い事に関して",
    body: "現在、子どもは未就学児なのですが、いつ頃から習い事を始めましたか？可能であれば、始めたきっかけや良かった点、悪かった点や何の習い事が良かったかも教えていただきたいです。",
  },
  {
    end_user_id: 2,
    title: "月々の住居費の負担割合について。",
    body: "現在借家で、子ども（未就学児）と夫婦の三人暮らしです。戸建て購入を検討しています。月々の支払はどのくらいが良いですか？ネットで調べて大体の金額は分かったのですが、実際はそれで生活が苦しくならないか心配です。実体験を伺いたいです。",
  },
  {
    end_user_id: 3,
    title: "一人暮らしの食費に関して",
    body: "現在、一人暮らしです。最近、地方から上京してきました。食費が思いのほか掛かっていて、貯金が出来ずに悩んでいます。自炊もしていますが、学業とアルバイトがあり疲れたときはお弁当を購入する等して、月に大体5～6万円ほどの出費です。高いですよね？",
  },
  {
    end_user_id: 3,
    title: "時短料理",
    body: "一人暮らしです。毎日料理を作るのが面倒くさいです。みなさんは毎日料理を作っているのでしょうか？",
  },
  {
    end_user_id: 3,
    title: "ブイヨン",
    body: "先ほど、レシピを調べていたら、ブイヨンと出てきました。ネットで検索してもよく分かりません。ベーコンで代用できますか？",
  },
  {
    end_user_id: 3,
    title: "引っ越し費用はどのくらい掛かりますか？",
    body: "一人暮らしです。経済的にきついので友人とシェアルームするか悩んでいます。現在は東京に住んでいるのですが、東京だと引っ越し費用も高いですか？実際、どのくらい掛かるのか教えていただきたいです。",
  },
  {
    end_user_id: 3,
    title: "友人とのシェアルームに関して",
    body: "友人とシェアルームをするか検討中です。理由は、経済的な理由です。友人は仲いい人で大丈夫かなと思う気持ちと、シェアルームで万が一関係が悪くなるのもいやだなと思い悩んでいます。経験がある方がいらっしゃれば実経験を教えていただきたいです。",
  },
  {
    end_user_id: 4,
    title: "節約の方法に関して",
    body: "将来の家購入や子どもの学費のためにお金を貯めたいのですが、なかなか貯まりません。収入が多くないというのもあるのですが、平均年収くらいはあると思います。まずは、食費が7万円近く掛かっているのでそれを4万円以下にしたいと思っています。食費の節約方法を教えてください！",
  },
  {
    end_user_id: 4,
    title: "子どもを産むタイミングに関して",
    body: "現在、共働きで出産後も働きたいと思っているのですが、その場合出産のタイミングはいつ頃がいいのでしょうか？社会人は5年目ですが、転職したばかりです。1年は早いかな？と思いつつ年齢も気になってきています。",
  },
  {
    end_user_id: 4,
    title: "私立校はやはり高いですか？",
    body: "出来るだけ子どもの選択肢を狭めたくなく、どこでもいいよのスタンスで子育てしたいのですが、実際の私立の費用が分からないので、正直不安です。どのくらいが目安というか一般的なのでしょうか？",
  },
  {
    end_user_id: 4,
    title: "共働き世帯の方",
    body: "旦那さんはどのくらい家事をしてくれていますか？うちはほとんど私です。こんなこと言っては何ですが、給与は夫婦でそんなに差がないです。私も家事が好きではないので折半にしたいのですが、皆さんはどうされていますか？",
  },
  {
    end_user_id: 4,
    title: "出産費用に関して",
    body: "出産費用ってどのくらい掛かりますか？東京ではないですが、関東住みですが一時金の範囲で収まりましたか？",
  },
  {
    end_user_id: 5,
    title: "子どもの学費に関して",
    body: "現在、子ども1人（未就学児）です。あともう一人子どもが欲しいのですが、学費はどのくらい見込めばいいのでしょうか？",
  },
  {
    end_user_id: 5,
    title: "私立校の学費に関して",
    body: "子どもを中学校から私立に行かせた場合と、高校から私立に行かせた場合でどのくらい違いますか？",
  },
  {
    end_user_id: 5,
    title: "こどものお小遣いに関して",
    body: "小学校高学年になる子どもがいます。子どもからお小遣いが少ないと言われたのですが、皆さんはどのくらいあげていますか？ちなみに、現在は2,000円です。",
  },
  {
    end_user_id: 5,
    title: "義実家帰省頻度に関して",
    body: "義実家に帰省する頻度ってどのくらいですか？",
  },
  {
    end_user_id: 5,
    title: "子どもの卒園式に関して",
    body: "子どもの卒園式って泣きましたか？余り実感がわかなくて、私自身はそんなに泣くタイプではないと思うのですが、どうなのでしょうか？",
  },
  {
    end_user_id: 6,
    title: "食費が多い気がするのですがこんなものですか？",
    body: "毎月、食費が8万円掛かっています。未就学児2人（男女）と夫婦の４人家族です。お米なんかも自分たちで購入しております。多い少ないのや節約するために行っていることがあれば教えてください！",
  },
  {
    end_user_id: 6,
    title: "卵無し料理に関して",
    body: "下の子が卵アレルギーで、卵を使用した料理が食べられません。ただ、卵を入れない料理ってすごく少ないと思っていて、レパートリーがありません。卵アレルギーを持つお子さんを育てている方、育てたことがある方どのようにされていましたか？",
  },
  {
    end_user_id: 6,
    title: "子ども3人は厳しいですか？",
    body: "平均年収家庭です。それで子ども3人って厳しいですか？",
  },
  {
    end_user_id: 6,
    title: "戸建て派？集合住宅派？",
    body: "住むならどちらがいいのでしょうか？私は強いこだわりがなく、単純にメリットデメリットを伺いたいです。",
  },
  {
    end_user_id: 6,
    title: "ペットに関して",
    body: "子どもがペットを飼いたいといっています。飼ってもいいし、何なら私も欲しいと思うのですが、容易ではないと思っています。注意点を教えていただきたいです。",
  },
  {
    end_user_id: 6,
    title: "美容院の頻度に関して",
    body: "美容院は何回ほど行っていますか？専業主婦ですが、独身の頃から月1回いっていたので、今までそのペースで行っていたのですが、先日、夫がとあるきっかけでそのことを知り多くない？と言われました。多いですか？",
  },
])


Tag.create!(
  [{
    name: "#食費",
  },
  {
    name: "#節約",
  },
  {
    name: "#4人家族",
  },
  {
    name: "#貯金",
  },
  {
    name: "#一人暮らし",
  },
  {
    name: "#戸建て購入",
  },
  {
    name: "#学費",
  },
  {
    name: "#3人家族",
  },
  {
    name: "#引っ越し時期",
  },
  {
    name: "#子どもの習い事",
  },
  {
    name: "#住居費",
  },
  {
    name: "#時短料理",
  },
  {
    name: "#ブイヨン",
  },
  {
    name: "#引っ越し費用",
  },
  {
    name: "#シェアルーム",
  },
  {
    name: "#平均年収世帯",
  },
  {
    name: "#子どもを産むタイミング",
  },
  {
    name: "#私立の費用",
  },
  {
    name: "#共働き",
  },
  {
    name: "#家事負担",
  },
  {
    name: "#出産費用",
  },
  {
    name: "#子どものお小遣い（高学年）",
  },
  {
    name: "#義実家の帰省頻度",
  },
  {
    name: "#卒園式",
  },
  {
    name: "#卵アレルギー",
  },
  {
    name: "子ども3人",
  },
  {
    name: "#どっち派？（住居）",
  },
  {
    name: "#ペット",
  },
  {
    name: "#美容院",
  },

])

MiddleOfTag.create!(
  [{
    consultation_id: 1,
    tag_id: 4,
  },
  {
    consultation_id: 1,
    tag_id: 6,
  },
  {
    consultation_id: 1,
    tag_id: 8,
  },
  {
    consultation_id: 2,
    tag_id: 6,
  },
  {
    consultation_id: 2,
    tag_id: 8,
  },
  {
    consultation_id: 2,
    tag_id: 9,
  },
  {
    consultation_id: 3,
    tag_id: 2,
  },
  {
    consultation_id: 3,
    tag_id: 4,
  },
  {
    consultation_id: 3,
    tag_id: 8,
  },
  {
    consultation_id: 4,
    tag_id: 10,
  },
  {
    consultation_id: 5,
    tag_id: 8,
  },
  {
    consultation_id: 5,
    tag_id: 11,
  },
  {
    consultation_id: 6,
    tag_id: 1,
  },
  {
    consultation_id: 6,
    tag_id: 5,
  },
  {
    consultation_id: 7,
    tag_id: 12,
  },
  {
    consultation_id: 8,
    tag_id: 13,
  },
  {
    consultation_id: 9,
    tag_id: 14,
  },
  {
    consultation_id: 10,
    tag_id: 15,
  },
  {
    consultation_id: 11,
    tag_id: 2,
  },
  {
    consultation_id: 11,
    tag_id: 16,
  },
  {
    consultation_id: 12,
    tag_id: 17,
  },
  {
    consultation_id: 13,
    tag_id: 18,
  },
  {
    consultation_id: 14,
    tag_id: 19,
  },
  {
    consultation_id: 14,
    tag_id: 20,
  },
  {
    consultation_id: 15,
    tag_id: 21,
  },
  {
    consultation_id: 16,
    tag_id: 18,
  },
  {
    consultation_id: 17,
    tag_id: 18,
  },
  {
    consultation_id: 18,
    tag_id: 22,
  },
  {
    consultation_id: 19,
    tag_id: 23,
  },
  {
    consultation_id: 20,
    tag_id: 24,
  },
  {
    consultation_id: 21,
    tag_id: 1,
  },
  {
    consultation_id: 21,
    tag_id: 3,
  },
  {
    consultation_id: 22,
    tag_id: 25,
  },
  {
    consultation_id: 23,
    tag_id: 16,
  },
  {
    consultation_id: 23,
    tag_id: 26,
  },
  {
    consultation_id: 24,
    tag_id: 27,
  },
  {
    consultation_id: 25,
    tag_id: 28,
  },
  {
    consultation_id: 26,
    tag_id: 29,
  },
])

SourceOfIncome.create!(
  [{
    end_user_id: 1,
    source_name: "GEST株式会社",
  },
  {
    end_user_id: 1,
    source_name: "副収入（短期）",
  },
  {
    end_user_id: 2,
    source_name: "二コ二コ株式会社",
  },
  {
    end_user_id: 2,
    source_name: "副収入（派遣）",
  },
])

AccountBook.create!(
  [{
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-8-25,
    book_date: 2022-9-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-7-25,
    book_date: 2022-8-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-6-25,
    book_date: 2022-7-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-5-25,
    book_date: 2022-6-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-4-25,
    book_date: 2022-5-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-3-25,
    book_date: 2022-4-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-2-25,
    book_date: 2022-3-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2022-1-25,
    book_date: 2022-2-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2021-12-25,
    book_date: 2022-1-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2021-11-25,
    book_date: 2021-12-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2021-10-25,
    book_date: 2021-11-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2021-9-25,
    book_date: 2021-10-1
  },
  {
    end_user_id: 1,
    source_of_income_id: 1,
    income: 180000,
    pay_day: 2021-8-25,
    book_date: 2021-9-1
  },
  {
    end_user_id: 1,
    source_of_income_id: 2,
    income: 9600,
    pay_day: 2022-8-1,
    book_date: 2022-8-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 2,
    income: 5600,
    pay_day: 2022-3-14,
    book_date: 2022-4-1,
  },
  {
    end_user_id: 1,
    source_of_income_id: 2,
    income: 10200,
    pay_day: 2022-1-7,
    book_date: 2022-1-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-8-25,
    book_date: 2022-9-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-7-25,
    book_date: 2022-8-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-6-25,
    book_date: 2022-7-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-5-25,
    book_date: 2022-6-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-4-25,
    book_date: 2022-5-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-3-25,
    book_date: 2022-4-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-2-25,
    book_date: 2022-3-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2022-1-25,
    book_date: 2022-2-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2021-12-25,
    book_date: 2022-1-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2021-11-25,
    book_date: 2021-12-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2021-10-25,
    book_date: 2021-11-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2021-9-25,
    book_date: 2021-10-1
  },
  {
    end_user_id: 2,
    source_of_income_id: 3,
    income: 200000,
    pay_day: 2021-8-25,
    book_date: 2021-9-1
  },
  {
    end_user_id: 2,
    source_of_income_id: 4,
    income: 5800,
    pay_day: 2022-8-1,
    book_date: 2022-8-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 4,
    income: 6400,
    pay_day: 2022-3-14,
    book_date: 2022-4-1,
  },
  {
    end_user_id: 2,
    source_of_income_id: 4,
    income: 4200,
    pay_day: 2022-1-7,
    book_date: 2022-1-1,
  },
])

SavingsEstination.create!(
  [{
   end_user_id: 1,
   savings_estination_name: "GEST銀行（定期預金）",
  },
  {
   end_user_id: 1,
   savings_estination_name: "GEST投資信託",
  },
  {
   end_user_id: 2,
   savings_estination_name: "二十二銀行（定期預金）",
  },
  {
   end_user_id: 2,
   savings_estination_name: "二〇〇投資信託",
  },
])

DepositBalance.create!(
  [{
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-8-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-7-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-6-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-5-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-4-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-3-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-2-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2022-1-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2021-12-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2021-11-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2021-10-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2021-9-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 1,
  savings_amount: 20000,
  deposit_date: 2021-8-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 2,
  savings_amount: 5000,
  deposit_date: 2022-8-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 2,
  savings_amount: 5000,
  deposit_date: 2022-4-1,
  },
  {
  end_user_id: 1,
  savings_estination_id: 2,
  savings_amount: 10000,
  deposit_date: 2022-1-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-8-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-7-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-6-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-5-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-4-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-3-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-2-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2022-1-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2021-12-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2021-11-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2021-10-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2021-9-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 3,
  savings_amount: 30000,
  deposit_date: 2021-8-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 4,
  savings_amount: 10000,
  deposit_date: 2022-8-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 4,
  savings_amount: 6000,
  deposit_date: 2022-4-1,
  },
  {
  end_user_id: 2,
  savings_estination_id: 4,
  savings_amount: 11000,
  deposit_date: 2022-1-1,
  },
])

BopSubject.create!(
  [{
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-8-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-7-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-6-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-5-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-4-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-3-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-2-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-1-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-12-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-11-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-10-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-9-1,
  },
  {
    end_user_id: 1,
    subject_name: "電気代",
    bop: 1,
    total_price: 7000,
    point: 0,
    use_at: 2021-8-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-8-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-7-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-6-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-5-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-4-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-3-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-2-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-1-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-12-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-11-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-10-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-9-1,
  },
  {
    end_user_id: 1,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7000,
    point: 0,
    use_at: 2021-8-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-8-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-6-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-4-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-2-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2021-12-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2021-10-1,
  },
  {
    end_user_id: 1,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2021-8-1,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-8-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-7-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-6-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-5-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-4-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-3-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-2-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-1-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-12-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-11-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-10-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-9-25,
  },
  {
    end_user_id: 1,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-8-25,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-8-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-7-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-6-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-5-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-4-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-3-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-2-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-1-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-12-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-11-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-10-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-9-27,
  },
  {
    end_user_id: 1,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-8-27,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-8-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-7-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-6-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-5-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-4-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-3-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-2-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-1-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-12-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-11-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-10-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-9-1,
  },
  {
    end_user_id: 2,
    subject_name: "電気代",
    bop: 1,
    total_price: 7000,
    point: 0,
    use_at: 2021-8-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-8-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 8000,
    point: 0,
    use_at: 2022-7-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-6-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-5-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-4-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 4500,
    point: 0,
    use_at: 2022-3-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-2-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2022-1-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-12-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7500,
    point: 0,
    use_at: 2021-11-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-10-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 5000,
    point: 0,
    use_at: 2021-9-1,
  },
  {
    end_user_id: 2,
    subject_name: "ガス代",
    bop: 1,
    total_price: 7000,
    point: 0,
    use_at: 2021-8-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-8-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-6-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-4-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2022-2-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2021-12-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2021-10-1,
  },
  {
    end_user_id: 2,
    subject_name: "水道代",
    bop: 1,
    total_price: 3500,
    point: 0,
    use_at: 2021-8-1,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-8-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-7-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-6-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-5-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-4-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-3-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-2-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2022-1-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-12-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-11-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-10-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-9-25,
  },
  {
    end_user_id: 2,
    subject_name: "家賃",
    bop: 1,
    total_price: 55000,
    point: 0,
    use_at: 2021-8-25,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-8-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-7-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-6-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-5-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-4-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-3-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-2-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2022-1-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-12-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-11-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-10-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-9-27,
  },
  {
    end_user_id: 2,
    subject_name: "携帯代",
    bop: 1,
    total_price: 4200,
    point: 0,
    use_at: 2021-8-27,
  },
])